### ISSUE TITLE
first time true, second time false password

### ISSUE THREAD

**Issue by sandman4812av** [TunisianEagles/SocialBox#1]
Hi
i want to test it and made list where put true fb password in it
socialbox found that password true, but now (2nd, 3rd) time it doesn't find that pass as true
what is wrong ?
thanks !

**Comment by TunisianEagles** [comment]
I Think u have a problem in Your internet , Try it again if it happends tell me

**Comment by sandman4812av** [comment]
thanks i solved it, but there is other problem
![image](https://user-images.githubusercontent.com/29623610/46146827-d1ffd780-c274-11e8-82df-0c25c01bb45b.png)
it is here code
cd Gemail-Hack
python gemailhack.py

and i made it python2, pyhon3 but no any good result

**Comment by TunisianEagles** [comment]
Install python , apt-get update && apt-get install python
