### ISSUE TITLE
No Success on GMail

### ISSUE THREAD

**Issue by bucky67gto** [TunisianEagles/SocialBox#2]
Ran against test user.  Never found password although inserted into dictionary to try.  Went right past it.

Thoughts?

**Comment by joebxxx** [comment]
How can i use this on android phone?

**Comment by TunisianEagles** [comment]
i will upgrade the tool soon , bucky67gto 
joebxxx , actually it Dosen't Support Android Right now , But the next upgrade it will be

**Comment by bucky67gto** [comment]
Thanks.  I know gmail is a moving target....like nailing jello to a wall..thanks for the update

**Comment by TunisianEagles** [comment]
joebxxx ok ;)
bucky67gto np mate ;)
