### ISSUE TITLE
wordlist cant find

### ISSUE THREAD

**Issue by Mamallann** [TunisianEagles/SocialBox#4]
Enter Facebook ID / Email / Username / Number: victim id
Enter wordlist path : '/root/tools/SocialBox/mamallan.lst' 

[-] No Wordlist On '/root/tools/SocialBox/mamallan.lst' -_- 
 		[+] Brute Force Complete [✓] [+]

what do to,i create a wordlist using cupp,but it cant take my wordlist

**Comment by TunisianEagles** [comment]
remove the quotes put it like that /root/tools/SocialBox/mamallan.lst

**Comment by Fedeara001** [comment]
How to enter wordlist in SocialBox

**Comment by PRA-not661** [comment]
Worldlist path main kya dalna hai

**Comment by doorman8** [comment]
i cant figure out the word list path either im super new at this and ive spent like the last eight hours  trying to figure it out

**Comment by Lukajmiq** [comment]
Can't locate Net/SSLeay/Handle.pm in @INC (you may need to install the Net::SSLeay::Handle module) (@INC contains: /data/data/com.termux/files/usr/lib/perl5/site_perl/5.36.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/site_perl/5.36.0 /data/data/com.termux/files/usr/lib/perl5/5.36.0/aarch64-android /data/data/com.termux/files/usr/lib/perl5/5.36.0) at fb-brute.pl line 41.
BEGIN failed--compilation aborted at fb-brute.p


What should I do?

**Comment by codebreaker5675** [comment]
If i want to brute force a instagram account, how can i do?
