### ISSUE TITLE
Does Not Work: sees correct password but keep on going as if it is wrong + '@' is turn to '%40'

### ISSUE THREAD

**Issue by AbdelXY** [TunisianEagles/SocialBox#6]
Dear Team,
I start your tool and it went through many passwords one by one and when it reaches the correct password in the work list. Unfortunately, it keeps on going and going.
**Also '@' is turn in '%40' which could be wrong** 
**Please fix it: it needs to stop at the correct password**

Many thanks for your hard work

**Comment by TunisianEagles** [comment]
There's New Update Soon ..

**Comment by jepunband** [comment]
yup does not work...skips pass the correct password.
